name: 'Define Version Need Changed'
description: 'Determines if project needs version bump based on its own changes or its dependencies'
inputs:
  changes:
    description: 'JSON string of changes for each project from define-project-has-changed'
    required: true
  projects_path:
    description: 'Path to projects.json'
    required: true
    default: '.github/config/projects.json'
outputs:
  needs_change:
    description: 'JSON object determining if a project needs a version change'
    value: ${{ steps.check.outputs.needs_change }}
runs:
  using: "composite"
  steps:
    - name: Evaluate version need
      id: check
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        node ${{ github.action_path }}/main.js '${{ inputs.changes }}' '${{ inputs.projects_path }}'
