<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>InsonusK.Shared.Command.Interface</PackageId>
    <Description>Shared command interfaces</Description>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="./../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
