<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>InsonusK.Shared.Command.Service.Interface</PackageId>
    <Description>Shared command service interfaces</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="MediatR" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="../../Command.Interface/InsonusK.Shared.Command.Interface/InsonusK.Shared.Command.Interface.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../Entities/DataBase/InsonusK.Shared.DataBase/InsonusK.Shared.DataBase.csproj" >
      <Version>1.3.0</Version>
    </ProjectReference>
  </ItemGroup>
  
  <ItemGroup>
    <None Include="./../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
  
</Project>
