name: 'Detect Changes'
description: 'Detect if project source code changed'

inputs:
  project-folder:
    description: 'Folder path to monitor (e.g. src/Models/**)'
    required: true

outputs:
  changed:
    description: 'Whether the project files have changed'
    value: ${{ steps.filter.outputs.project }}

runs:
  using: "composite"
  steps:
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          project:
            - '${{ inputs.project-folder }}'
