name: Project Unit tests

on:
  pull_request:
    branches: [ master, develop ]

permissions:
  contents: read
  pull-requests: read
  
env:
  src_path: 'src/**'

jobs:
  check_changing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository src
      uses: actions/checkout@v3
    - name: Check does src or test changed
      uses: dorny/paths-filter@v2
      id: changed_obj
      with:
        filters: |
          src:
            - ${{ env.src_path }}
    
    outputs:
      src_changed: ${{ steps.changed_obj.outputs.src }}  

  testing:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:9.0
    needs: check_changing
    if: ${{ needs.check_changing.outputs.src_changed == 'true' }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run project unit tests
        uses: ./.github/workflows/jobs/testing.yaml
  