name: Push to Master - Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  load-matrix:
    uses: ./.github/workflows/get-matrix.yml

  build-and-publish:
    needs: load-matrix
    strategy:
      matrix: ${{ fromJSON(needs.load-matrix.outputs.matrix) }}
      fail-fast: false
    
    uses: ./.github/workflows/project-pipeline.yaml
    with:
      project-folder: ${{ matrix.project.folder }}
      csproj: ${{ matrix.project.csproj }}
      package-id: ${{ matrix.project.package-id }}
      artifact-name: ${{ matrix.project.artifact }}
      create-release: true
      owner: ${{ github.repository_owner }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      nuget-token: ${{ secrets.NUGET_TOKEN }}